version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: hugomka
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw test
      - store_artifacts:
          path: target/site/jacoco/index.html

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: hugomka
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2

  test-with-store-artifacts:
    jobs:
      - test